services:
  nginx:
    build: ./nginx
    image: kontursvet-nginx-prod
    #image: kontursvet-nginx-dev
    container_name: nginx_prod
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - '7080:80'
      - '7443:443'
    depends_on:
      - nuxt
    volumes:
      - ./nginx/ssl/kontursvet:/etc/letsencrypt/live/kontursvet/
      - ./nginx/ssl/:/etc/letsencrypt

  nuxt:
    build: .
    image: kontursvet-nuxt-prod
    #image: kontursvet-nuxt-dev
    container_name: nuxt_prod
    env_file:
      - .env.prod
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    volumes:
      - ./logs:/nuxtapp/logs
    restart: always
