services:
  nginx:
    build: ./nginx
    container_name: nginx
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - '7080:80'
      - '7443:443'
    depends_on:
      - nuxt
    volumes:
      - ./nginx/ssl/kontursvet:/etc/letsencrypt/live/kontursvet/
      - ./nginx/ssl/:/etc/letsencrypt

  nuxt:
    build: .
    container_name: nuxt
    environment:
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - SMTP_FROM=${SMTP_FROM}
      - SMTP_TO=${SMTP_TO}
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - '3000:3000'
    restart: always
